name: App Service Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

env:
  ENVIRONMENT_PREFIX: ${{ vars.ENVIRONMENT_PREFIX }}
  AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}

jobs:
  deploy:
    runs-on: windows-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Debug
        run: |
          echo ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
          echo ENVIRONMENT_PREFIX: ${{ env.ENVIRONMENT_PREFIX }}
          echo ARTIFACT_NAME: ${{ vars.ARTIFACT_NAME }}
          echo AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}

      - uses: actions/download-artifact@v4
        with:
          name: ${{ vars.ARTIFACT_NAME }}-${{ env.ENVIRONMENT_PREFIX }}
          path: './_build'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Publish Artifacts to Azure
        uses: Azure/webapps-deploy@v2
        with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}                       
            package: './_build'
      
      - name: logout
        run: |
          az logout