name: App Service Build

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Debug
        run: |
          echo ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
          echo ENVIRONMENT_PREFIX: ${{ vars.ENVIRONMENT_PREFIX }}
          echo SOLUTION_FILE: ${{ vars.SOLUTION_FILE }}
          echo MS_BUILD_ARGS: ${{ vars.MS_BUILD_ARGS }}
          echo MS_BUILD_PLATFORM: ${{ vars.MS_BUILD_PLATFORM }}
          echo MS_BUILD_CONFIGURATION: ${{ vars.MS_BUILD_CONFIGURATION }}

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
        
      - name: Restore Nuget Packages
        run: nuget restore ${{ vars.SOLUTION_FILE }}

      - name: Create Build Directory
        run: |
          cd $GITHUB_WORKSPACE
          mkdir _build

      - name: Restore the application
        run: |
          msbuild ${{ vars.SOLUTION_FILE }} ${{ vars.MS_BUILD_ARGS }} /p:platform=${{ vars.MS_BUILD_PLATFORM }} /p:Configuration=${{ vars.MS_BUILD_CONFIGURATION }} /p:PublishUrl='../_build'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.ARTIFACT_NAME }}-${{ vars.ENVIRONMENT_PREFIX }}
          path: "./_build"